### PR TITLE
Added docker-compose.yml file to concurrently run both backend and frontend docker files.

### PR DESCRIPTION
**Pull request by bahebwashidah**
This pull request includes Dockerization of the frontend and backend services of the project. Two separate Docker images were created for the frontend and backend, and a docker-compose.yml file was added to manage the services. The frontend Dockerfile is located within the frontend directory, while the backend Dockerfile is in the base directory.

- Created Dockerfile for both frontend and backend services.
- Configured docker-compose.yml to build and run both services on separate ports.
- Set up Docker Compose to ensure the frontend runs on port 3000 and the backend on port 5000.

Related Issue
Fixes # (issue)

Type of Change
 Enhancement(non-breaking change which adds functionality)
How Has This Been Tested?
The changes have been tested by running the Docker Compose setup and verifying the services are accessible at their respective ports.

1.  Tested running docker-compose up --build to start both services.
2.  Verified that the frontend is running on http://localhost:3000 and the backend on http://localhost:5000.
3.  Cleaned up unused Docker images and containers after verifying functionality.

Checklist:

-  Code follows the style guidelines of this project.
-  A self-review of the code has been performed.
-  Code is commented, particularly in hard-to-understand areas.
-  Corresponding changes have been made to the documentation.
-  Changes generate no new warnings.
-  Tests have been added to prove the fix is effective or that the feature works.
-  New and existing unit tests pass locally with the changes.
-  Any dependent changes have been merged and published in downstream modules.

## Summary by CodeRabbit

- **New Features**
	- Introduced a multi-service application with `backend`, `frontend`, and `web` services.
	- Added a new dependency on the `express` library for enhanced functionality.
	- Implemented a health check mechanism to monitor application status.

- **Bug Fixes**
	- Updated the server's default port from 3000 to 5000 to align with the new configuration.

- **Documentation**
	- Added Dockerfiles for both backend and frontend applications to streamline deployment.
	- Introduced a `.dockerignore` file to optimize the Docker build process.
	- Updated Nginx configuration for serving the frontend application.

### CODE REVIEW

**Comment by MartinKalema** [comment]
Hi @bahebwashidah,  pls share a screenshot of the app running in the docker environment. Also, resolve coderrabbit's suggestions.

**Comment by bahebwashidah** [comment]
images of the app running in the docker environment

**Comment by MartinKalema** [comment]
Hi @bahebwashidah, Kindly drop the images within another comment as they cannot be viewed through your email reply.
email

Attached is a picture highlighting the icon used to attach files to comments.
button

**Comment by bahebwashidah** [comment]
containers
frontend
backend

**Review by MartinKalema — APPROVED** [review]
Thanks @bahebwashidah .

**Pull request merged**
